### ISSUE TITLE
C# examples

### ISSUE THREAD

**Issue by SidGrundfos** [openfaas-incubator/nats-connector#6]
Hello Team,
This is not really an issue, but need help with C# examples.

**Comment by SidGrundfos** [comment]
I have used the sample given but I do not receive the messages. The only difference is that I have the NATS cluster in a different namespace. The publish message sends the messages successfully. But the receive message has no response.

**Comment by alexellis** [comment]
Hi, please could you use Slack for technical support? Alternatively, if this is part of a work project, we do provide professional services via OpenFaaS Ltd https://www.openfaas.com/support/ and would be more than happy to help with years of C# experience.
